# Generated by Django 4.1.6 on 2023-02-13 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 15, 45, 35, 789620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
